name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build All Components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install client dependencies
        run: |
          cd client
          make deps

      - name: Build client
        run: |
          cd client
          make build

      - name: Build client for all platforms
        run: |
          cd client
          make build-all

      - name: Build server
        run: |
          cd server
          make build

      - name: Upload client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-binaries
          path: client/dist/
          retention-days: 7

      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/build/
          retention-days: 7 